### ISSUE TITLE
XPath - wrong argument syntax?

### ISSUE THREAD

**Issue by neatc0der** [michaelw/mediathek-dl#1]
Hi there,

first of all, thanks for this code. Second, I believe I've found an issue concerning the path execution within mediathek-dl. I keep getting the following error message:
Cannot open file '-q' at /usr/share/perl5/vendor_perl/XML/XPath.pm line 53

Btw. I'm using OS X (10.9.4), maybe that's the problem?

**Comment by michaelw** [comment]
Hi, indeed the OS X xpath is broken/different, you need this one:
http://search.cpan.org/dist/XML-XPath/  (On Debian/Ubuntu, this is in package libxml-xpath-perl).  Let me know whether this fixes it for you.

However, note that they are changing Mediathek html/rss so often, that it becomes difficult to keep this script working reliably.
